// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Stopper is an autogenerated mock type for the Stopper type
type Stopper struct {
	mock.Mock
}

// Stop provides a mock function with given fields:
func (_m *Stopper) Stop() {
	_m.Called()
}
