// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import pkg "todo/pkg"

// OptionsProvider is an autogenerated mock type for the OptionsProvider type
type OptionsProvider struct {
	mock.Mock
}

// GetTodoOptions provides a mock function with given fields:
func (_m *OptionsProvider) GetTodoOptions() *pkg.TodoOptions {
	ret := _m.Called()

	var r0 *pkg.TodoOptions
	if rf, ok := ret.Get(0).(func() *pkg.TodoOptions); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.TodoOptions)
		}
	}

	return r0
}
